var _ = require('underscore');
var util = require('util');
var path = require('path');
var fs = require('fs');
var tap = require('tap');
var mongoose = require('mongoose');
mongoose.set('debug', true);

/**
 * note - this test is dependant on data generated by the sunlight test.
 *
 */
var connection = "mongodb://localhost/test_ico_data_50189";
mongoose.connect(connection);

tap.test('icodata', {timeout: 1000 * 1000, skip: false }, function (suite) {
    var icod = require('./../index.js');
    suite.test('map-reduce', {timeout: 1000 * 1000, skip: false }, function (mr_test) {

        var client = new icod.Client(0, true);

        client.map_reduce_sector_data('sun_cos', 'sun_cosines', function(err, results){
            console.log('done with mr: %s', err, util.inspect(results));
            mr_test.end();
        }, 0);
    });

    suite.end();

});